### ISSUE TITLE
Script should also check ssh service (not only sshd) to rate ssh setup

### ISSUE THREAD

**Issue by beejaz** [healthyhost/audit-vps-script#3]
Hey! Nice tool & website, I tried it out and found that it is not working 100% accurate on my setup for the SSH parts.

Here, the script is only looking for `sshd` service. Some systems doesn't have `sshd` service but they have `ssh` service instead.

https://github.com/healthyhost/audit-vps-script/blob/1eb4bfce6a18349557ecab6df1fe6eae67cc65cf/audit.sh#L237C8-L237C27

```bash
x@server:~$ sudo systemctl status sshd
Unit sshd.service could not be found.
x@server:~$ sudo systemctl status ssh
● ssh.service - OpenBSD Secure Shell server
     Loaded: loaded (/usr/lib/systemd/system/ssh.service; disabled; preset: enabled)
     Active: active (running) since Wed 2024-10-02 17:46:57 UTC; 2 months 12 days ago
TriggeredBy: ● ssh.socket
       Docs: man:sshd(8)
             man:sshd_config(5)
   Main PID: 1097 (sshd)
      Tasks: 1 (limit: 4543)
     Memory: 4.9M (peak: 12.2M)
        CPU: 55min 2.948s
     CGroup: /system.slice/ssh.service
             └─1097 "sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups"
```

```bash
x@server:~$ sudo systemctl is-active sshd
inactive
x@server:~$ sudo systemctl is-active ssh
active
```

```bash
x@server:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
```

Would be awesome if it could be changed to support both 🙏

**Comment by kkyr** [comment]
Hey @beejaz thanks for reporting this.

I'm considering modifying the script to not read the file and instead parse the output of `sshd -T`. This way there's no dependency on the location of the file.

That being said, I took a deeper look at your case. I think the SSH service that you have installed is the SSH client, i.e. the program that is used to connect to SSH servers. If this is the case, it means you don't have an SSH server installed on your system and you should not be able to connect to it via SSH.

Can you please verify if this is the case?

**Comment by beejaz** [comment]
> Hey @beejaz thanks for reporting this.
> 
> I'm considering modifying the script to not read the file and instead parse the output of `sshd -T`. This way there's no dependency on the location of the file.
> 
> That being said, I took a deeper look at your case. I think the SSH service that you have installed is the SSH client, i.e. the program that is used to connect to SSH servers. If this is the case, it means you don't have an SSH server installed on your system and you should not be able to connect to it via SSH.
> 
> Can you please verify if this is the case?

Hi! I do have a ssh server/service, im connected to it during these commands. Its up and running on port 22, this is a ubuntu vps on Hetzner cloud

**Comment by kkyr** [comment]
Oh, apologies for assuming otherwise.

Then something must be starting an SSH server.

Can you please check what process is listening on port 22 by running `sudo lsof -i :22`?

**Comment by kkyr** [comment]
@beejaz #9 introduces a change that might fix this issue you're facing. Do you please mind trying again with the latest version of the script?

**Comment by beejaz** [comment]
Hi! It works much better now, just like I wanted! Thank you

**Comment by kkyr** [comment]
Fantastic, thank you!
