### ISSUE TITLE
SSH service reported as disabled while I am SSH'ed onto the server

### ISSUE THREAD

**Issue by JapSeyz** [healthyhost/audit-vps-script#7]
Hey,

I probably don't understand the check, but I am curious as to why it reports the "SSH Service is disabled"; while I am actively using SSH on the server to run the check?

![image](https://github.com/user-attachments/assets/cf5cd044-1ed4-4cb6-9a16-ceb8fb2692fc)

Sidenote, there may also be an issue with the status of one of the steps:
![image](https://github.com/user-attachments/assets/6d75b934-8987-4cf9-839f-6e409bac2d26)

**Comment by JapSeyz** [comment]
I am not sure why the ssh_jail_enabled check fails either:

![image](https://github.com/user-attachments/assets/1ec61b95-c16a-4ef0-bdc2-ed90314ccd4c)

![image](https://github.com/user-attachments/assets/7e1f087c-5873-4eec-8db9-360aa5fa3fc0)

**Comment by kkyr** [comment]
Hey @JapSeyz , thanks for opening this issue.

> I probably don't understand the check, but I am curious as to why it reports the "SSH Service is disabled"; while I am actively using SSH on the server to run the check?

Likely related to #3. The check relies on `sshd` running. Can you please let me know what program is running the SSH server on your system? You can see this by running `sudo lsof -i :22` (assuming SSH is running on port 22).

> Sidenote, there may also be an issue with the status of one of the steps:

I changed one of the check names yesterday and it seems you have an older version of the script. Please download the latest version and it should work!

> I am not sure why the ssh_jail_enabled check fails either

Any chance you have another instance of `[sshd]` in the jail file? If not, could you please send me the file so I can reproduce locally? You can find my email on auditvps.com if you don't want to share it here.

**Comment by JapSeyz** [comment]
As far as I can tell, it is `sshd`

![image](https://github.com/user-attachments/assets/6880bd2f-998c-45a5-a7eb-6f3e5a0781de)


> I changed one of the check names yesterday and it seems you have an older version of the script. Please download the latest version and it should work!

I ran the one-liner from auditvps.com, could it be that the script wasn't updated there?

> Any chance you have another instance of [sshd] in the jail file?

I don't believe so, I just added a very basic example, as I didn't have the file before the check.
`grep`ing "sshd" does however return two instances.
![image](https://github.com/user-attachments/assets/d0d980fa-7528-4749-b4e2-0706df304256)

Are you checking for `[sshd]` or just `sshd`?

**Comment by kkyr** [comment]
> As far as I can tell, it is sshd

Mind sharing the output of `systemctl is-active sshd` please?

> I ran the one-liner from auditvps.com, could it be that the script wasn't updated there?

Oops, I missed updating the check when it's skipped, apologies. Opening a PR now.

> Are you checking for [sshd] or just sshd?

It's checking for `[sshd]` at the start of the line. Is there whitespace preceding it?

**Comment by JapSeyz** [comment]
> systemctl is-active sshd

`inactive` curious.

> It's checking for [sshd] at the start of the line. Is there whitespace preceding it?

There's a blank link preceding it, that's it. No other whitespace.
![image](https://github.com/user-attachments/assets/29b945d4-1cf8-4bc4-ae85-9fc816a12d12)

**Comment by kkyr** [comment]
> inactive curious.

Interesting. What's output of `systemctl list-units | grep -I ssh`?

> There's a blank link preceding it, that's it. No other whitespace.

I've tried reproducing with the contents in the image but I'm unable to. Mind sending me the entire file? There shouldn't be anything sensitive in it (but please double check before you do!). You can send it via email kyri@auditvps.com if you prefer.

**Comment by JapSeyz** [comment]
> systemctl list-units | grep -I ssh

![image](https://github.com/user-attachments/assets/4ff61105-d895-4884-a88a-ab4e51eeac1f)

> You can send it via email [kyri@auditvps.com](mailto:kyri@auditvps.com) if you prefer.

Sent

**Comment by kkyr** [comment]
@JapSeyz I think I was able to fix them both and I updated the script on the server. Can you please try again?

**Comment by JapSeyz** [comment]
Seems to work 🎉 
![image](https://github.com/user-attachments/assets/2a8a2320-9953-42d8-9717-6e8e349a62f7)

**Comment by kkyr** [comment]
Fantastic! Thank you for helping make it more robust 🙏

Closing as it's resolved!
